- name: Set variables for passive nodes
  set_fact:
    group_nodes: "{{ group_value }}"
    active_node: "{{ group_value | selectattr('active', 'equalto', true) | first }}"
    passive_nodes: "{{ group_value | selectattr('active', 'equalto', false) | list }}"

- name: Create directory for passive nodes
  file:
    path: "{{ passive_node_dir }}"
    state: directory
    mode: "{{ file_permissions }}"
  loop: "{{ passive_nodes }}"
  loop_control:
    label: "{{ node.service_tag }}"
    loop_var: node

- name: Generate corosync.conf for passive nodes (same as active)
  template:
    src: "{{ corosync_tmpl }}"
    dest: "{{ corosync_tmpl_dest }}"
  vars:
    active_node: "{{ active_node }}"
    passive_nodes: "{{ passive_nodes }}"
    node: "{{ node }}"
  loop: "{{ passive_nodes }}"
  loop_control:
    label: "{{ node.service_tag }}"
    loop_var: node

- name: Generate pcs container file for passive nodes
  template:
    src: "{{ pcs_container_tmpl }}"
    dest: "{{ pcs_container_tmpl_dest }}"
  vars:
    node_info: "{{ node }}"
  loop: "{{ passive_nodes }}"
  loop_control:
    label: "{{ node.service_tag }}"
    loop_var: node

- name: Generate pcs-start.sh for passive nodes
  template:
    src: "{{ pcs_start_tmpl }}"
    dest: "{{ pcs_start_tmpl_dest }}"
    mode: "{{ file_permissions }}"
  vars:
    node: "{{ node }}"
  loop: "{{ passive_nodes }}"
  loop_control:
    label: "{{ node.service_tag }}"
    loop_var: node
